### ISSUE TITLE
Použít negativní podmínku, kde to dává smysl

### ISSUE THREAD

**Issue by xtompok** [hofrajtm/du1#2]
Pokud je větev za if prázdná, je lepší použít opačnou podmínku. Rovněž použít, pokud je jediným příkazem ve větvi za if identita (např. u=u;)

**Comment by hofrajtm** [comment]
Připomínky opraveny, dokumentaci dodám ještě dnes.

**Comment by xtompok** [comment]
Pokud připomínku opravíš, je dobré Issue zavřít pomocí Close Issue.
